[workspace]
members = [
  "scripts/source/prepare_ci_pubsub",
  "src/batch",
  "src/bench",
  "src/cmd",
  "src/cmd_all",
  "src/common",
  "src/common/common_service",
  "src/compute",
  "src/connector",
  "src/ctl",
  "src/expr",
  "src/expr/macro",
  "src/frontend",
  "src/frontend/planner_test",
  "src/java_binding",
  "src/meta",
  "src/object_store",
  "src/prost",
  "src/prost/helpers",
  "src/risedevtool",
  "src/risedevtool/config",
  "src/rpc_client",
  "src/source",
  "src/sqlparser",
  "src/sqlparser/test_runner",
  "src/storage",
  "src/storage/backup",
  "src/storage/backup/cmd",
  "src/storage/compactor",
  "src/storage/hummock_sdk",
  "src/storage/hummock_test",
  "src/stream",
  "src/test_runner",
  "src/tests/compaction_test",
  "src/tests/e2e_extended_mode",
  "src/tests/regress",
  "src/tests/simulation",
  "src/tests/sqlsmith",
  "src/tests/state_cleaning_test",
  "src/udf",
  "src/utils/local_stats_alloc",
  "src/utils/pgwire",
  "src/utils/runtime",
  "src/utils/sync-point",
  "src/utils/workspace-config",
  "src/workspace-hack",
]

[workspace.package]
version = "1.0.0-alpha"
edition = "2021"
homepage = "https://github.com/risingwavelabs/risingwave"
keywords = ["sql", "database", "streaming"]
license = "Apache-2.0"
repository = "https://github.com/risingwavelabs/risingwave"

[workspace.dependencies]
await-tree = "0.1.1"
aws-config = { version = "0.55", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-credential-types = { version = "0.55", default-features = false, features = ["hardcoded-credentials"] }
aws-sdk-kinesis = { version = "0.28", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-sdk-s3 = { version = "0.28", default-features = false, features = ["rt-tokio","native-tls"] }
aws-sdk-ec2 = { version = "0.28", default-features = false, features = ["rt-tokio","native-tls"] }
aws-sdk-sqs = { version = "0.28", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-smithy-client = { version = "0.55", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-smithy-http = "0.55"
aws-smithy-types = "0.55"
aws-endpoint = "0.55"
aws-types = "0.55"
etcd-client = { package = "madsim-etcd-client", version = "0.3" }
futures-async-stream = "0.2"
hytra = "0.1"
rdkafka = { package = "madsim-rdkafka", git = "https://github.com/madsim-rs/madsim.git", rev = "79cfa9d", features = ["cmake-build"] }
hashbrown = { version = "0.14.0", features = ["ahash", "inline-more", "nightly"] }
criterion = "0.5"
tonic = { package = "madsim-tonic", version = "0.3.1" }
tonic-build = { package = "madsim-tonic-build", version = "0.3.1" }

[profile.dev]
lto = 'off'

[profile.release]
debug = 1
lto = 'thin'

# The profile used for CI in main branch.
# This profile inherits from the release profile, but turns on some checks and assertions for us to
# better catch bugs in CI.
[profile.ci-release]
inherits = "release"
incremental = false
debug = "line-tables-only"
debug-assertions = true
overflow-checks = true

# The profile used for CI in pull requests.
# External dependencies are built with optimization enabled, while crates in this workspace are built
# with `dev` profile and full debug info. This is a trade-off between build time and e2e test time.
[profile.ci-dev]
inherits = "dev"
incremental = false
debug = "line-tables-only"
[profile.ci-dev.package."*"] # external dependencies
opt-level = 1
[profile.ci-dev.package."tokio"]
opt-level = 3
[profile.ci-dev.package."await-tree"]
opt-level = 3
[profile.ci-dev.package."indextree"]
opt-level = 3

# The profile used for deterministic simulation tests in CI.
# The simulator can only run single-threaded, so optimization is required to make the running time
# reasonable. The optimization level is customized to speed up the build.
[profile.ci-sim]
inherits = "dev"
opt-level = 2
incremental = false
debug = 1

# Patch third-party crates for deterministic simulation.
[patch.crates-io]
quanta = { git = "https://github.com/madsim-rs/quanta.git", rev = "948bdc3" }
getrandom = { git = "https://github.com/madsim-rs/getrandom.git", rev = "8daf97e" }
tokio-stream = { git = "https://github.com/madsim-rs/tokio.git", rev = "fe39bb8e" }
tokio-retry = { git = "https://github.com/madsim-rs/rust-tokio-retry.git", rev = "95e2fd3" }
tokio-postgres = { git = "https://github.com/madsim-rs/rust-postgres.git", rev = "4538cd6" }
