[meta]
disable_recovery = true
max_heartbeat_interval_secs = 600

[streaming]
in_flight_barrier_nums = 10

[system]
barrier_interval_ms = 5000
checkpoint_frequency = 1
max_concurrent_creating_streaming_jobs = 0
