[package]
name = "risingwave_hummock_sdk"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["workspace-hack", "num-traits"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
bytes = "1"
hex = "0.4"
itertools = "0.11"
parse-display = "0.8"
risingwave_common = { workspace = true }
risingwave_pb = { workspace = true }
tracing = "0.1"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }
